name = "NodeCall"
uuid = "84d67a5e-1aa2-4817-a501-81e0ebf70bff"
authors = ["Sunoru <s@sunoru.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
libjlnode_jll = "e3ef64f0-f261-50ad-b884-29c8a26457f8"
libnode_jll = "76d26698-d9ba-5ca1-ae24-4ac9393d02a0"

[compat]
RandomNumbers = "1"
julia = "1.6"
libjlnode_jll = "14"
libnode_jll = "14"
